trailingComma: 'es5'
tabWidth: 2
semi: false
singleQuote: true
arrowParens: always
bracketSameLine: false
bracketSpacing: true
embeddedLanguageFormatting: 'auto'
endOfLine: 'lf'
htmlWhitespaceSensitivity: 'css'
jsxSingleQuote: false
printWidth: 120
proseWrap: 'preserve'
quoteProps: 'as-needed'
singleAttributePerLine: false
plugins:
    - prettier-plugin-tailwindcss
